export const CART_ACTION_TYPES = {
    'ADD_CART_ITEM' : 'ADD_CART_ITEM',
    'REMOVE_CART_ITEM' : 'REMOVE_CART_ITEM',
    'CLEAR_CART_ITEM' : 'CLEAR_CART_ITEM',
    'TOGGLE_CART_OPEN' : 'TOGGLE_CART_OPEN'
}